apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sanitize-db
spec:
  schedule: "*/30 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: paranoidaditya/cron
            env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_NAME
              value: shopify_test    
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
          - name: cloudsql-proxy
            image: gcr.io/cloudsql-docker/gce-proxy:1.11
            command: ["sh", "-c"]
            args:
            - /cloud_sql_proxy -instances=shopify-w2019:northamerica-northeast1:hire-me=tcp:3306 -credential_file=/secrets/cloudsql/credentials.json & pid=$! && (sleep 60 && kill -9 $pid 2>/dev/null)
            securityContext:
              runAsUser: 2  # non-root user
              allowPrivilegeEscalation: false
            volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: cloudsql-instance-credentials
            secret:
              secretName: cloudsql-instance-credentials